version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: go run cmd/main.go
